"""Add joined_at field to user model

Revision ID: 895e9cad32bf
Revises: 620467d807fc
Create Date: 2022-05-27 01:43:39.082091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895e9cad32bf'
down_revision = '620467d807fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joined_at')
    # ### end Alembic commands ###
