"""Add article image_path field to Article model

Revision ID: 99f2c3ec9863
Revises: f1bda749bb2b
Create Date: 2022-05-25 21:52:17.890765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f2c3ec9863'
down_revision = 'f1bda749bb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('image_path', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image_path')
    # ### end Alembic commands ###
