"""Add subscriber relationship to User Model

Revision ID: da0017bd2a25
Revises: 530073a8afcd
Create Date: 2022-05-25 19:21:27.815786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0017bd2a25'
down_revision = '530073a8afcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_column('subscriber', 'is_subscriber')
    op.add_column('user', sa.Column('subscriber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'subscriber', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'subscriber_id')
    op.add_column('subscriber', sa.Column('is_subscriber', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'subscriber', ['user_id'], ['id'])
    # ### end Alembic commands ###
