"""Interchanged subscriber relationship to User Model

Revision ID: f1bda749bb2b
Revises: 65c8e83cdbca
Create Date: 2022-05-25 19:44:33.125393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bda749bb2b'
down_revision = '65c8e83cdbca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriber_user_id_fkey', 'subscriber', type_='foreignkey')
    op.drop_column('subscriber', 'user_id')
    op.add_column('user', sa.Column('subscriber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'subscriber', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'subscriber_id')
    op.add_column('subscriber', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subscriber_user_id_fkey', 'subscriber', 'subscriber', ['user_id'], ['id'])
    # ### end Alembic commands ###
